### ISSUE TITLE
Snakefile for running pipeline

### ISSUE THREAD

**Issue by HannahVMeyer** [single-cell-genetics/limix_qtl#17]
Thanks for creating a dedicated workflow for using limix in a eQTL setting.

We can see the python and R scripts, and wondered if the Snakefile that is referred to in the wiki and on the [CellRegMap](https://limix.github.io/CellRegMap/limix.html) website is also available.

Thanks!

**Comment by Bonder-MJ** [comment]
Hi,

Good catch. I thought it was online.
I'm adding it in the main dir.

Thanks!
