### ISSUE TITLE
np.object deprecated in numpy > 1.20

### ISSUE THREAD

**Issue by pl92297** [single-cell-genetics/limix_qtl#20]
Hello, 

The current recommended docker/singularity installation of limix_qtl involves installing numpy >1.21. Unfortunately, this results in an attribute error as np.object in the utils file was deprecated in numpy 1.20. Please update limix.def to load an older version of numpy.

Thanks!

**Comment by Bonder-MJ** [comment]
Hello,

Thanks for the message. I now forced it to numpy 1.21.
But will fix the underlaying change in the next few weeks.

Thanks,
Marc

**Comment by Bonder-MJ** [comment]
Fixed and updated throughout now. Thanks for the spot!
