### ISSUE TITLE
Random effects file.

### ISSUE THREAD

**Issue by AlexSimis** [single-cell-genetics/limix_qtl#24]
Greetings,

First of all, congratulations for your work on this tool. It's great to have such a versatile tool (especially for LMMs). 

So, I have protein abundance values from individuals at two different time points, hence for the cis-QTL mapping I want to run a mixed model that accounts for the correlation of values (within individual). However, I'm unsure about the structure of the "randomEffFile" that I should provide in order to incorporate the repeated measurements per individual - what should this file include?
Since the mapping file specifies the connection between genotype IDs and the corresponding phenotype IDs, I imagine that the "randomEffFile" will be something different than a simple dummy variable.

Best,
Alex.

**Comment by Bonder-MJ** [comment]
Hi Alex,

Thanks for reaching out!

The random effect file should show the relation between the measurements/samples. 

I normally use a kinship matrix, but you can also just use a dummy file with ones on the diagonal and zeros off diagonal. The file should be a matrix with the column and row names matching your genotype ids that you use in the genotype file (and sample mapping file). To be sure, the order doesn't matter and you only need to have the genotyped sample in your files once, the software expands the data automatically as needed based on the sample mapping file.

Best,
Marc
